<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AssemblyName>AcaciaCustomContentPatcher</AssemblyName>
    <Version>1.0.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Mono.Cecil">
      <HintPath>..\..\BepInEx\core\Mono.Cecil.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
